version: "3.1"

services:
  ovs:
    image: socketplane/openvswitch:2.4.0
    container_name: ovs
    ports:
      - "6640:6640"
    command: "/usr/bin/supervisord -n"
    privileged: true
  apiserver-server:
    build: ./docker
    container_name: apiserver-server
    links:
      - ovs
      - apiserver-db
    volumes:
       - $HOME/go:/go
    working_dir: /go/src/apiserver
    ports:
      - 8081:8080
    tty: true
  apiserver-db:
      image: mysql:5.7.25
      container_name: apiserver-db
      # deploy:
      # replicas: 1
      restart: always
      ports:
        - 3306:3306
      volumes:
        - ~/etc/timezone:/etc/localtime:ro
        - ./apiserver-db/db-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root