FROM golang:latest

RUN apt-get update && \
apt-get install -y build-essential && \
apt-get install -y software-properties-common && \
apt-get install -y curl git vim wget   &&\
apt-get install openssl -y

RUN mkdir $GOPATH/git.esix.com/
RUN mkdir $GOPATH/git.esix.com/jackyczj/
WORKDIR $GOPATH/git.esix.com/jackyczj/

WORKDIR $GOPATH/git.esix.com/jackyczj/go-restfulovn
RUN go install .
RUN go build -o RemoteOVN .

RUN ./RemoteOVN